import pathlib
import textwrap


AGENT_TEMPLATES = {
    "agent.py": textwrap.dedent("""\
        from pika.agent import BaseAgent


        class {ClassName}(BaseAgent):
            agent_id    = '{name}'
            description = 'Describe what this agent does'

            instructions = [
                'Be concise',
                'Cite sources when possible',
            ]
    """),
    "prompts/system.j2": textwrap.dedent("""\
        You are a helpful assistant. Today is {{ current_date }}.

        {% if active_corrections %}
        ## Active Instructions
        {% for c in active_corrections %}
        - {{ c }}
        {% endfor %}
        {% endif %}
    """),
    "prompts/demonstrations.yaml": "# Auto-generated by pika optimize\n",
    "training_examples.yaml": textwrap.dedent("""\
        # Add input/output examples for pika optimize
        # - input: example user message
        #   output: ideal agent response
    """),
    "tests/test_{name}.py": textwrap.dedent("""\
        import pytest
        from pika.testing.harness import AgentTestHarness
        from agents.{name}.agent import {ClassName}


        @pytest.fixture
        def harness():
            return AgentTestHarness(
                agent_class={ClassName},
                mock_responses=['Mock response'],
            )


        @pytest.mark.asyncio
        async def test_basic(harness):
            result = await harness.run('Hello')
            assert result.content
    """),
}


def _render_template(content: str, name: str, class_name: str) -> str:
    return content.replace("{name}", name).replace("{ClassName}", class_name)


def scaffold(kind: str, name: str):
    if kind == "agent":
        base = pathlib.Path("agents") / name
        class_name = "".join(w.capitalize() for w in name.split("_")) + "Agent"
        for rel_template, content in AGENT_TEMPLATES.items():
            rel = rel_template.format(name=name)
            path = base / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.exists():
                path.write_text(_render_template(content, name, class_name))
        (base / "__init__.py").touch()
        print(f"Scaffolded agent: agents/{name}/")
        print(f"Next: add to registry.yaml, then pika chu {name}")

    elif kind == "tool":
        base = pathlib.Path("tools") / name
        base.mkdir(parents=True, exist_ok=True)
        (base / "__init__.py").touch()
        tool_file = base / "tool.py"
        class_name = "".join(w.capitalize() for w in name.split("_")) + "Tool"
        if not tool_file.exists():
            tool_file.write_text(
                textwrap.dedent(f"""\
                from agno.tools import tool as agno_tool
                from pika.tool import BaseTool


                class {class_name}(BaseTool):
                    tool_id = '{name}'

                    @agno_tool(description='Describe what this tool does')
                    async def run(self, input: str) -> str:
                        raise NotImplementedError
            """)
            )
        print(f"Scaffolded tool: tools/{name}/")
    else:
        print(f'Unknown kind: {kind}. Use "agent" or "tool".')
